### ISSUE TITLE
Support extension to Markdown (umbrella issue)

### ISSUE THREAD

**Issue by nojb** [ocaml/omd#205]
This is an umbrella issue for requested extensions to Markdown. In principle there is a desire to support these, but we need to introduce a proper extension API first.

- [ ] GFM-style tables (#188)
- [ ] Latex/Math support (#107, #194)
- [ ] Wiki-style links ? (#117)
- [ ] Footnotes (#149)

**Comment by nojb** [comment]
No plans to address this, let's close.
